version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]